# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Carles Matoses Gimenez
name: Carles Matoses Gimenez
email: carlesmatosesg@gmail.com
youtube: channel/UC6aWlHNMv-VGU7LRBeZaj7w
linkedin_username: carles-matoses-b2b9a82b7
github_username:  carlesmatoses

description: >- # this means to ignore newlines until "baseurl:"
  Carles Matoses Gimenez works as my portfolio where I upload relevant and recent works. 
  I'm a computer graphics student with a degree in multimedia technologies. I'm interested in open source softwares, photography and visual effects. 
  I spend some of my time studiying blender as well as game engines!!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
keywords: Computer Graphics, Programming, Python, Blender, Render, Rendering, Game Engines, Real Time Rendering, Fast Realistic Rendering

# Build settings
theme: minima
plugins:
  - jekyll-feed

toc:
  min_level: 1
  max_level: 6
  no_toc_section_class: "no_toc"
  list_class: "toc-list"
  sublist_class: "toc-sublist"
  item_class: "toc-item"
  item_prefix: "toc-item-"
  list_number: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
