[project]
name = "carlesmatoses-github-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "carles-pc", email = "carlesmatosesg@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.4.0",
    "matplotlib>=3.11.2",
    "numpy>=2.4.6",
]

[project.scripts]
carlesmatoses-github-io = "carlesmatoses_github_io:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
